export const GET_DASHBOARD_OVERVIEW_DATA = "GET_DASHBOARD_OVERVIEW_DATA";
export const GET_ORGANIZATION_LIST = "GET_ORGANIZATION_LIST";
export const GET_FOLDER_OVERVIEW = "GET_FOLDER_OVERVIEW";
export const GET_SUBSCRIPTION_OVERVIEW = "GET_SUBSCRIPTION_OVERVIEW";
export const HANDLE_VERIFY_DOCUMENTS = "HANDLE_VERIFY_DOCUMENTS";
export const HANDLE_SYNCED_FILE_FILTER = "HANDLE_SYNCED_FILE_FILTER";
export const HANDLE_DOCUMENT_VERIFICATION_DATA_FILTER =
  "HANDLE_DOCUMENT_VERIFICATION_DATA_FILTER";
export const SET_INITIALSTATE = "SET_INITIALSTATE";
export const SET_APIFLAGS_INITIALSTATE = "SET_APIFLAGS_INITIALSTATE";
export const SOCKET_DOCUMENT_VERIFICATION_PROGRESS =
  "SOCKET_DOCUMENT_VERIFICATION_PROGRESS";
export const SOCKET_DOCUMENT_VERIFICATION_RESULT =
  "SOCKET_DOCUMENT_VERIFICATION_RESULT";
export const SOCKET_DOCUMENT_UPLOAD_LIMIT_EXCEEDED_ERROR =
  "SOCKET_DOCUMENT_UPLOAD_LIMIT_EXCEEDED_ERROR";
export const GET_DOCUMENT_HASH_BLOCKCHAIN_PROOF =
  "GET_DOCUMENT_HASH_BLOCKCHAIN_PROOF";
export const GET_ORGANIZATION_EXHIBIT_BLOCKCHAIN_PROOF =
  "GET_ORGANIZATION_EXHIBIT_BLOCKCHAIN_PROOF";
export const GET_EXHIBIT_BLOCKCHAIN_PROOF = "GET_EXHIBIT_BLOCKCHAIN_PROOF";
export const GET_LAB_EXHIBIT_BLOCKCHAIN_PROOF =
  "GET_LAB_EXHIBIT_BLOCKCHAIN_PROOF";
export const UPDATE_DOCUMENT_EFFECTIVE_DATE = "UPDATE_DOCUMENT_EFFECTIVE_DATE";
export const GET_FOLDER_PATH = "GET_FOLDER_PATH";
