export const GET_DASHBOARD_OVERVIEW_DATA = "GET_DASHBOARD_OVERVIEW_DATA";
export const GET_ORGANIZATION_LIST = "GET_ORGANIZATION_LIST";
export const GET_FOLDER_OVERVIEW = "GET_FOLDER_OVERVIEW";
export const HANDLE_VERIFY_DOCUMENTS = "HANDLE_VERIFY_DOCUMENTS";
export const HANDLE_SYNCED_FILE_FILTER = "HANDLE_SYNCED_FILE_FILTER";
export const SET_INITIALSTATE = "SET_INITIALSTATE";
export const SOCKET_DOCUMENT_VERIFICATION_PROGRESS =
  "SOCKET_DOCUMENT_VERIFICATION_PROGRESS";
